### ISSUE TITLE
Add code for generating the IBM Validated Software List

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#100]
@arshPratap used code he shared here https://github.com/arshPratap/SDT-Validated-Open-Source-List/blob/main/Validated_OpenSource.ipynb to generate the data files for the IBM Validated Software List, but this code has not yet been incorporated into this repository.

We could add this to package_build.py but my inclination is to create a separate script that allows you to specify which distributions from the list you want to build the JSON for.

**Comment by xtanion** [comment]
Hi @pleia2, Can I work on this issue?
thanks

**Comment by Princee215** [comment]
Hey guys. I am new to open source and have experience with web development, and this issue seems to be suitable for me

**Comment by Princee215** [comment]
Could you assign this issue to me @arshPratap?

**Comment by arshPratap** [comment]
@Princee215 feel free to work on this. Looking forward to see your work on this

**Comment by xtanion** [comment]
Hi @Princee215 Have you started working on this issue? I've already started working on the issue.
