### ISSUE TITLE
Fix creation of Rocky Linux 9 source

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#103]
The archive we point to for version 9.0 of Rocky Linux 9 has been moved to their vault, so the script no longer generates these sources properly. Update the script, probably to point to just "9" rather than continually updating it for each point release (it's at 9.1 now).

**Comment by aashish-khatri** [comment]
@pleia2 I've made a pull request for the assigned issue, I've updated the link as mentioned, and it seems to be working fine now,
