### ISSUE TITLE
Add support to package_build.py for Ubuntu 23.04

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#108]
Update bin/package_build.py and to add support for the latest release of Ubuntu, 23.04.

**Comment by arshPratap** [comment]
hey @pleia2 looks like ubuntu has their own package search tool..directly scrapping off packages from that seems a bit counter-intuitive to me

**Comment by pleia2** [comment]
Most of them do, in fact the one for openSUSE searches several different distros! But folks didn't like being pointed at a bunch of different websites to search, which is why we created this consolidated tool. One spot, search everything 😄

**Comment by pratham1729** [comment]
yep @pleia2 @arshPratap that's what I had observed when i picked the issue up,  we were basically scraping off data from package download websites for all the other distros. So would my PR be considered valid now?

**Comment by pleia2** [comment]
So I realized we can just pull from data provided by the PDS project for Ubuntu, they've now updated their repository here https://github.com/linux-on-ibm-z/PDS/blob/master/distro_data/Ubuntu_23_04_Package_List.json

Apologies for making you do double-work! I'll close this one out, Ubuntu, Red Hat Enterprise Linux, and SUSE Linux Enterprise Server should always default to PDS data.

**Comment by pratham1729** [comment]
Oh no worries it was fun diving through stuff and finding a lot of things which i may use in the future :)
