### ISSUE TITLE
Document importing data sources

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#11]
This project was forked from Package Distro Search (PDS), which contained data sources in the repository in a distro_data/ directory, so it automatically included everything needed to run out of the box.

We made the architecture decision to split out the code from the data for this project, so the documentation needs to be updated to reflect this, including sources for the data.

Tips for this documentation update: We can still point people to https://github.com/linux-on-ibm-z/PDS/tree/master/distro_data as a data source. We will also have a new OMP project for data, but that project has not yet been created.

**Comment by rachejazz** [comment]
Regarding this issue, git submodules is tried and tested. I can go ahead with the documentation of this part
