### ISSUE TITLE
Optimized approach for adding ubuntu 23.04 as a data source

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool#118]
In response to issue #108, I found out that instead of manually searching for every software tool on a given link and then scrapping the needed data, why not just load all data from here https://packages.ubuntu.com/lunar/s390x/allpackages

@arshPratap @pleia2, any thoughts?

**Comment by pleia2** [comment]
It turns out that there's a team at IBM in this project that's already providing Ubuntu sources in the format we need, so we don't need to worry about Ubuntu sources after all! https://github.com/linux-on-ibm-z/PDS/tree/master/distro_data

**Comment by Princee215** [comment]
No worries... 😄 in case any need is required in the future, do let me know. I would love to work on the issue.
