### ISSUE TITLE
Fixing import bugs

### ISSUE THREAD

**Issue by indranilm256** [openmainframeproject/software-discovery-tool#12]
1. Paths in the src folder still reference the PDS directory, need to be changed to software-discovery-tool. 
2. The log file is missing, giving the following errors:
```{r}
________________ ERROR collecting test_json.py ________________
test_json.py:7: in <module>
    from config.config import server_host
../config/__init__.py:1: in <module>
    from .config import *
../config/config.py:75: in <module>
    logging.basicConfig(format='%(asctime)s %(message)s', filename=LOG_FILE_LOCATION, level=DEBUG_LEVEL)
/usr/lib/python3.8/logging/__init__.py:1976: in basicConfig
    h = FileHandler(filename, mode)
/usr/lib/python3.8/logging/__init__.py:1143: in __init__
    StreamHandler.__init__(self, self._open())
/usr/lib/python3.8/logging/__init__.py:1172: in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
E   FileNotFoundError: [Errno 2] No such file or directory: '/opt/software-discovery-tool/log/pds.log'
_______________ ERROR collecting test_render.py _______________
test_render.py:6: in <module>
    from config.config import server_host
../config/__init__.py:1: in <module>
    from .config import *
../config/config.py:75: in <module>
    logging.basicConfig(format='%(asctime)s %(message)s', filename=LOG_FILE_LOCATION, level=DEBUG_LEVEL)
/usr/lib/python3.8/logging/__init__.py:1976: in basicConfig
    h = FileHandler(filename, mode)
/usr/lib/python3.8/logging/__init__.py:1143: in __init__
    StreamHandler.__init__(self, self._open())
/usr/lib/python3.8/logging/__init__.py:1172: in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
E   FileNotFoundError: [Errno 2] No such file or directory: '/opt/software-discovery-tool/log/pds.log'
```
3. collections packages imported but not used in package_search.py leads to DeprecationWarning:
```{r}
  /usr/local/lib/python3.8/dist-packages/requests/packages/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping, MutableMapping
```

**Comment by pleia2** [comment]
1 & 2 are addressed in the now merged PR #13

**Comment by pleia2** [comment]
@indranilm256 Do you want to have a look at #3? If it's not being used, we may be better off removing it.

**Comment by indranilm256** [comment]
@pleia2 I'll give it a look. Can you assign this issue to me.

**Comment by rachejazz** [comment]
Hey @pleia2 there was config error that has been resolved.
![image](https://user-images.githubusercontent.com/42383989/121560662-5e5a8480-ca35-11eb-9c4e-0a06cbcf5250.png)
 @indranilm256 had asked me to look into :))
config error was both in SUSE and ubuntu
Does anybody know who put this `config.config` here? Problem was here itself
![image](https://user-images.githubusercontent.com/42383989/121560798-7b8f5300-ca35-11eb-9fdd-bb5995487ea4.png)



currently trying to resolve the rest 2 warnings. Will send a PR right after:
![image](https://user-images.githubusercontent.com/42383989/121560412-1b001600-ca35-11eb-9af0-2f24a8ff098b.png)

**Comment by rachejazz** [comment]
linked issue #28

**Comment by indranilm256** [comment]
We can close this issue, warnings were  local to my system. Using a python virtual environment solved it
