### ISSUE TITLE
Need to correct the OS Listed in Deployed Version 

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool#126]
I found out that in the deployed version of our website, in the FAQ section, the operating systems for which SDT have data files, are not correct and just showing a few of them as can be seen in the screenshot that I've attached.

![SDT](https://github.com/openmainframeproject/software-discovery-tool/assets/80761691/e22a2631-1005-45b9-859c-44b932eb83a2)

But, when I checked the code, all the OS are updated.

![OS_list](https://github.com/openmainframeproject/software-discovery-tool/assets/80761691/0ef13f9c-b11d-4b94-b659-95f55132e655)

We need to solve this issue. @pleia2 and @arshPratap any thoughts?

**Comment by pleia2** [comment]
I have manually updated the version in production, but this has nothing to do with the project itself and is only a production problem.

Can you open a new Issue in https://github.com/openmainframeproject/software-discovery-tool-deploy to note that it doesn't appear that the core code is being updated reliably? I know this to be true, but we should have an open issue to start addressing this problem.

**Comment by Princee215** [comment]
Thanks @pleia2 for reviewing this issue. I've raised an issue accordingly as asked please take a look here https://github.com/openmainframeproject/software-discovery-tool-deploy/issues/10

**Comment by arshPratap** [comment]
@Princee215  Thanks for this !
