### ISSUE TITLE
creating a ci/cd pipeline for complete automation of deployment procedure

### ISSUE THREAD

**Issue by maheshkasabe** [openmainframeproject/software-discovery-tool#129]
since the deployment part of the tool is still done by manually we really need a ci/cd pipeline to automate our deployment task further to production. we can add various types of practices while building our pipeline since our code is on github gitops can be beneficial for us, what do you think @pleia2 & @arshPratap ??

**Comment by pleia2** [comment]
We have a basic implementation of this using GitHub Actions in this repository https://github.com/openmainframeproject/software-discovery-tool-deploy so that's where you'll want to start with enhancements to the process, there are a few open bugs about parts where it's a bit broken in production.

**Comment by maheshkasabe** [comment]
Thank you @pleia2 i'll take a look!

**Comment by pleia2** [comment]
Closing in favor of specific issues in -deploy repository.
