### ISSUE TITLE
Fedora has moved 34, 35,& 36 releases to archive repository.

### ISSUE THREAD

**Issue by xtanion** [openmainframeproject/software-discovery-tool#130]
I was working on the automation script for the new distribution list, which we discussed in the last meeting. I found out that Fedora has moved all of their previous releases **up to** `Fedora 36` to https://archives.fedoraproject.org/pub/archive/fedora-secondary/releases/.

Please take a look @pleia2 & @arshPratap . I'll be happy to work on the fix.

**Comment by arshPratap** [comment]
@xtanion thanks for this.. We will definitely keep this in mind while working for the discussed automation script. I am technically waiting for the mentorship to begin to start some work on this and when the mentorship begins we can keep this issue in mind. Thanks!

**Comment by xtanion** [comment]
Thanks for the response @arshPratap , It should be an easy fix, we just need to modify the url and check which distros have been moved to the archive repo. 
Please let me know, Thanks.
