### ISSUE TITLE
Add Debian 12 to bin/package_build.py

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#144]
Debian 12 has now been released! So we want to add it to our package_build.py script.

**Comment by Princee215** [comment]
Sure, @pleia2 I'll work on it and try to add it too as soon as possible.

**Comment by arshPratap** [comment]
@Princee215 is it alright if I assign this to @aashish-khatri ?

**Comment by Princee215** [comment]
Sure, @arshPratap, let @aashish-khatri do the work. I might help him by reviewing the code for adding Debian 12.
