### ISSUE TITLE
FIx the creation of OpenSUSE data files

### ISSUE THREAD

**Issue by arshPratap** [openmainframeproject/software-discovery-tool#145]
Currently, all the OpenSUSE data files that are being generated have an empty JSON file. It would be great to have a fix for this issue and subsequently update the data files in the data repo

**Comment by arshPratap** [comment]
@aashish-khatri would like to know your thoughts on this ?

**Comment by aashish-khatri** [comment]
Hi @arshPratap, I would like to work on this issue, I think we would have to look into the opensuse module and make sure everything is working properly.

**Comment by arshPratap** [comment]
Alright ! @aashish-khatri I have assigned this issue to you

**Comment by arshPratap** [comment]
hi @cboltz ..thanks for the response

**Comment by pleia2** [comment]
@cboltz Would you mind taking a look at the raw data files we're now producing, and are in this PR? https://github.com/openmainframeproject/software-discovery-tool-data/pull/61

A quick glance is giving me hope https://raw.githubusercontent.com/openmainframeproject/software-discovery-tool-data/f3f3ca7decbdab1370a5ed90fcc45a71e615e80f/data_files/OpenSUSE_Leap_15_4.json

**Comment by cboltz** [comment]
These json files look good and correct (at least for a few packages i checked).

Only nitpicking: it's `openSUSE`, not `OpenSUSE` or `Opensuse` ;-)

**Comment by pleia2** [comment]
Thank you, @cboltz!

And branding is important, so we'll be more diligent about the proper capitalization in the application moving forward :+1:
