### ISSUE TITLE
Update UI of website of SDT with new framework react with tailwind CSS 

### ISSUE THREAD

**Issue by devhimanshuu** [openmainframeproject/software-discovery-tool#170]

**Comment by rachejazz** [comment]
@devhimanshuu are you a new contributor or willing to participate in the mentorship? This topic is already highlighted and has an ongoing PR. You might want to take a look at them.


Closing issue in a week if inactive.

**Comment by devhimanshuu** [comment]
yeah i want to contribute through mentorship ?

**Comment by aadhil2k4** [comment]
Hi, I also wanna contribute to this via the mentorship. Is there any steps that i should follow?

**Comment by rachejazz** [comment]
Hey @devhimanshuu @aadhil2k4 please be on the lookout for opening dates for proposals on https://mentorship.lfx.linuxfoundation.org/
Till then, you could participate in meetings help on OMP slack channel, thanks!

Closing due to aforementioned reasons

**Comment by devhimanshuu** [comment]
> Hey @devhimanshuu @aadhil2k4 please be on the lookout for opening dates for proposals on https://mentorship.lfx.linuxfoundation.org/ Till then, you could participate in meetings help on OMP slack channel, thanks!
> 
> Closing due to aforementioned reasons

how can i join slack channel it need a official email to join from linux foundation
