### ISSUE TITLE
Fix installation docs

### ISSUE THREAD

**Issue by rachejazz** [openmainframeproject/software-discovery-tool#172]
There are few uncharted areas in the installation process.
1. How to create sdtreaduser
2. The readme.md or contribute.md should have link to the installation wiki so that it's easier to find it. (Thanks @Ash-2k3 )
3. Why is it a requirement to grant low privileged access to user
4. Better placeholders to be used for passwords. ROOTPWD for root and SDTUSERPWD for clearer explanation.
5. In addition, recheck post db update documentation for any other missed areas.

**Comment by Ash-2k3** [comment]
One more suggestion:

The readme.md or contribute.md should have link to the [installation](https://github.com/openmainframeproject/software-discovery-tool/blob/master/docs/Installation.md) wiki so that it's easier to find it.

**Comment by rachejazz** [comment]
Updated!

**Comment by Ash-2k3** [comment]
I have opened a PR for this issue. PTAL, whenever you are free @rachejazz. Thanks :)
