### ISSUE TITLE
Add Fedora 39 and Fedora 40

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool#174]
Fedora 39 and Fedora 40 have support for s390x, so we should add script support for it as well.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by rachejazz** [comment]
@aarishshahmohsin please send PR if you want to work on it :)

**Comment by Ash-2k3** [comment]
Looks like a PR has been merged which addresses this issue: https://github.com/openmainframeproject/software-discovery-tool/pull/182. Maybe, it can be closed now ?
