### ISSUE TITLE
Broken link for IBM Validated Open Source List

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool#175]
The package source link for the IBM Validated Open Source List seems to be broken. 
Here's the link - https://www.ibm.com/community/z/open-source-software/output/json/

**Comment by pleia2** [comment]
This is the new link: https://community.ibm.com/zsystems/api/oss/json

**Comment by Ash-2k3** [comment]
Thanks @pleia2 for providing with the new link :). I have opened a PR to address this issue, PTAL.


/cc @Princee215 (Thanks)
