### ISSUE TITLE
Debian 10 has removed support for s390x

### ISSUE THREAD

**Issue by Princee215** [openmainframeproject/software-discovery-tool#176]
Debian 10 has removed support for s390x, therefore we should remove script support and data file for it.

**Comment by pleia2** [comment]
Debian 10 is an old release with extremely limited support overall, so :+1: to removing it from the script.

We should also remove Fedora 37 and older (see: https://docs.fedoraproject.org/en-US/releases/eol/) and openSUSE Leap 15.3 and 15.4 (see: https://endoflife.date/opensuse).

**Comment by Apurv428** [comment]
@Princee215 Does removing script means removing from the data_files?
`https://github.com/openmainframeproject/software-discovery-tool-data/tree/main/data_files`

**Comment by pleia2** [comment]
> @Princee215 Does removing script means removing the json from the data_files? `https://github.com/openmainframeproject/software-discovery-tool-data/tree/main/data_files`

Yes, we should also remove them from the data repository.

**Comment by Princee215** [comment]
> @Princee215 Does removing script means removing the json from the data_files? `https://github.com/openmainframeproject/software-discovery-tool-data/tree/main/data_files`

Yes, Apurv that would do the same as @pleia2 suggested.
