### ISSUE TITLE
Change supported_distros.py to an example file for easier deployment

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#197]
In production, it's recommended to use something like our https://github.com/openmainframeproject/software-discovery-tool-deploy system which updates the production tool with every commit so that the tool automatically stays up to date.

Today it doesn't quite work because changes often have to be made to supported_distros.py in production instances to list all of the supported distributions and software lists, causing a conflict when `git pull` runs.

Instead, we should have supported_distros.py**.example** file that we maintain for the project, which continues to serve the purpose of showing all the sources we support, and also serves as a helpful starting place for folks implementing in production.

What needs to be done:

1. supported_distros.py renamed to supported_distros.py.example
2. A .gitignore entry added for src/config/supported_distros.py
3. Installation documentation updated indicating that the .example file should be copied to supported_distros.py and modified to reflect the distributions your deployment supports

**Comment by deveshidwivedi** [comment]
I'd like to work on this! @pleia2
