### ISSUE TITLE
Remaining PDS rename tasks

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#20]
If you grep through the repository there are several files that still reference PDS. These should be updated, and the code tested where code changes are required (like config.py).

**Comment by indranilm256** [comment]
I have completed most of rename tasks in src folder in new PR.

**Comment by rachejazz** [comment]
I'm guessing this is done by @indranilm256 through #25 ?

**Comment by indranilm256** [comment]
Yes major renaming tasks done. We can close this
