### ISSUE TITLE
update ubuntu distro version?

### ISSUE THREAD

**Issue by rachejazz** [openmainframeproject/software-discovery-tool#22]
installation docs shows ubuntu's version <18
Shouldn't it be updated? I am working on ubuntu 20 server edition and it runs the tool smoothly.
Here's a snippet. Any issues in ubuntu <18 can't find any support
![image](https://user-images.githubusercontent.com/42383989/118837516-85181600-b8e2-11eb-9967-0ee29b444e4b.png)

**Comment by pleia2** [comment]
Yes! Ubuntu 20.04 LTS should be the preferred installation target (18.04 LTS is still supported for a couple more years, but we shouldn't encourage using it, users can figure out for themselves if it works and they have to use it).

**Comment by indranilm256** [comment]
Yes, I think we should update the docs to mention newer versions of Ubuntu too, like 20.04, 20.10 and recently released 21.04(after testing on it) or it might seem misleading.

**Comment by pleia2** [comment]
Since those later versions are not Long Term Support releases, folks are less likely to run them in production on servers since support only lasts for 9 months (and it means we have a lot of documentation updating to do!). So I'd rather stick to the LTS releases: 20.04, and then next year's 22.04.

**Comment by rachejazz** [comment]
It'll be very weird to send a PR on only a distro version change. Should I update in the docs then?
Change -> Ubuntu 17 to Ubuntu 20.04(LTS)

**Comment by pleia2** [comment]
Please do! And I'll also go ahead and assign this issue to you.
