### ISSUE TITLE
Basic UI Improvements

### ISSUE THREAD

**Issue by rachejazz** [openmainframeproject/software-discovery-tool#26]
Agenda:
![image](https://user-images.githubusercontent.com/42383989/120484881-2027ea00-c3d1-11eb-9fd0-9acd32da3c6f.png)

Progress:
![image](https://user-images.githubusercontent.com/42383989/120478222-3ed6b280-c3ca-11eb-8e01-50a183d1398a.png)

Is this ok? Should I open a PR?

**Comment by pleia2** [comment]
Yes, go for it!

**Comment by rachejazz** [comment]
Yayy cool. Sending in awhile
