### ISSUE TITLE
Linking to Data Repo

### ISSUE THREAD

**Issue by indranilm256** [openmainframeproject/software-discovery-tool#33]
Update doc to reference to the data repository for sdt.

**Comment by indranilm256** [comment]
@pleia2 could you assign this to me. I'll look into the other repository too and add a Readme file with the link to this repository

**Comment by pleia2** [comment]
Great idea! Thanks for taking this.

**Comment by rachejazz** [comment]
Hey @indranilm256 keeping it here so that we need not search the repo name over and over again :')
https://github.com/openmainframeproject/software-discovery-tool-data

**Comment by indranilm256** [comment]
Addressed by @rachejazz in above mentioned PR
