### ISSUE TITLE
FAQ update regarding supported Operating systems

### ISSUE THREAD

**Issue by rachejazz** [openmainframeproject/software-discovery-tool#36]
![image](https://user-images.githubusercontent.com/42383989/123086914-9902ea80-d441-11eb-9403-865343258c3e.png)
- Since PDS had only Linux distros, this page had these. Need to add SDT's sources and change these to z/os, Debian and ClefOS sources
- "Supported Distros" need to be changed to "Supported OS" everywhere in the code
- And this:
![image](https://user-images.githubusercontent.com/42383989/123087301-057de980-d442-11eb-82de-db3e66df163d.png)

**Comment by indranilm256** [comment]
@pleia2 can you assign this to me
