### ISSUE TITLE
Error when calling searchPackages API

### ISSUE THREAD

**Issue by indranilm256** [openmainframeproject/software-discovery-tool#39]
I am getting the following error when calling the searchPackages API using 
`http://localhost/searchPackages?search_term=Gzip`:

`2021-06-27 21:22:21,309 Error in searchPackages with search parameters: 'bool' object has no attribute 'lower'
`

I could trace the error and it seems that in package_search.py, we are converting exact_match to lower case. 

https://github.com/openmainframeproject/software-discovery-tool/blob/05c73291a4b0551f995ded7d87dbb95a00acd163/src/classes/package_search.py#L170 

However, it is a boolean and needs to be cast to a string first. This can be done in main.py where we are passing the exact_match argument.

**Comment by rachejazz** [comment]
Not required, it was a builtin method mismatch
![image](https://user-images.githubusercontent.com/42383989/123552854-d941d000-d795-11eb-9753-edbdee5c98c2.png)
This solved the error. However API is not working, that's one of the tasks required to do this summer

**Comment by indranilm256** [comment]
Why are we replacing exact_match by search_term here?

**Comment by indranilm256** [comment]
Why are we replacing exact_match by search_term here?

**Comment by rachejazz** [comment]
exact_match for some reason is not defined inside package_search class. Still thinking it redundant. For exact match, we can just use "search_term" like google dorking.

**Comment by indranilm256** [comment]
exact_match is not defined in package_search, it is being passed from main to the searchPackages API, it basically checks if the match has to be an exact or not. So imo we shouldn't replace it with search_term. 

Also, I am able to retrieve the data now by using 

`http://localhost/searchPackages?search_term=zip&exact_match=False&search_bit_flag=1`

I'm not sure what the search_bit_flag does but apparently we have to set it to 1 for the search to work

**Comment by rachejazz** [comment]
Just tried the exact_match `lower()` method. It returns a string in lower case rather than a bool type. I think lower() should be islower()

Also with that, == 'true' equates to the string "true" rather than the bool `True`

Both are different. Needs to be fixed

**Comment by indranilm256** [comment]
Sure .lower() method will return a string, it is a method of the string class. We don't need to change anything in package_search, and the logic is fine in the if statement. All we need to do is pass the exact_search variable as a string from main.

**Comment by rachejazz** [comment]
true is not a bool type, True is

**Comment by indranilm256** [comment]
Yeah sure that's why I suggested the second option, we can keep exact_match as a bool and make it work as well

**Comment by pleia2** [comment]
> Or we can refactor the code in package_search as such:
> 
> `exact_match == True`

This solution would be my inclination.

Thanks to both of you for digging through this! It's kind of a mess :smiley:

**Comment by indranilm256** [comment]
Issue resolved by PR https://github.com/openmainframeproject/software-discovery-tool/pull/42
