### ISSUE TITLE
Document adding SUPPORTED_DISTROS to config.py

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#43]
After importing the JSON files in step 5 of the documentation, you also need to update config.py to add them under SUPPORTED_DISTROS (ZOS is the only one there by default). This should be documented.

Also, I just noticed there are now two steps labeled Step 6 - oops! Should fix this up while you're in there adding a step anyway :smile:

**Comment by rachejazz** [comment]
Ow sure. Let me handle this :)
With this issue I'll remove the default json files mentioned in config.py
And add a documentation regarding that.

Shouldn't these be in https://github.com/openmainframeproject/software-discovery-tool/blob/master/docs/Adding_new_distros.md ?

**Comment by pleia2** [comment]
Ok yes, so it IS actually kind of documented, but it's unclear in the installation documentation how to get from here to there, so maybe in Step 5 you can link to Step 2, or similar? https://github.com/openmainframeproject/software-discovery-tool/blob/master/docs/Adding_new_distros.md#step-2-update-the-supported_distros-variable-in-configuration-file-pds_basesrcconfigconfigpy

I'll leave the details to you :smile:

**Comment by rachejazz** [comment]
Yeah that's doable. Cool
