### ISSUE TITLE
z/OS name formatting

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#44]
Currently in the UI, z/OS is called ZOS. We want to be using the proper capitalization and include the forward slash, since that reflects what users will expect the operating system to be called.

**Comment by pleia2** [comment]
We may need to be generally sensitive to the trademark/branding here too, since it may be required to call it "IBM z/OS" and even include (TM) somewhere, but I'll inquire internally at IBM. This may also be true for the Linux distributions. For now, just updating it to z/OS will be sufficient.

**Comment by rachejazz** [comment]
I'll add this in my new PR too. Assign these to me
