### ISSUE TITLE
Update footer to link to Open Mainframe Project and GitHub

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#46]
Since this is a Linux Foundation Open Mainframe Project project, we'll want to reflect that in the footer.

Also add a link to the source code in GitHub, explaining that the code is available.

So the following Links should somehow be included in the refreshed text:

https://www.openmainframeproject.org/
https://www.openmainframeproject.org/projects/software-discovery-tool
https://github.com/openmainframeproject/software-discovery-tool

**Comment by indranilm256** [comment]
@pleia2 can you assign it to me, will try to resolve this too
