### ISSUE TITLE
Document creation of JSON files for Linux distributions

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#48]
When we generate the JSON files for Linux distributions like Debian and ClefOS, it's done programmatically. Document how this is done for each distribution we support, and add any scripts used in the bin/ directory to help future maintainers keep the sources updated.

**Comment by rachejazz** [comment]
I've already mentioned it here https://github.com/openmainframeproject/software-discovery-tool/blob/master/docs/Installation.md#using-data-from-pds

Do you need a separate doc for that?

**Comment by rachejazz** [comment]
Maybe a specific readme for the bin directory?
Which binary does what.

I'm going to include an autoconfig bin too, so...

**Comment by pleia2** [comment]
I'm referring to the project-side, how do WE update the Debian JSON file for inclusion in the -data project. We'll need to do an update at least every month to keep it fresh.

**Comment by rachejazz** [comment]
That should be simply 
```
./bin/package_build.py Debian
```
Every month :)

**Comment by pleia2** [comment]
Oh, I see! In the case of PDS it pulls from the GitHub repo, but for Debian it actually creates the file, rather than downloading it from our data repo. That'll do.
