### ISSUE TITLE
Describe what the site is on the main page

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#50]
There are some clues, since it has an Open Mainframe Project logo, and one of the default search options is z/OS, but it's still not obvious to a random person on the internet that this is a search tool for software packages on the Z architecture.

We should put some introductory wording (under the logo?) to explain what the tool is for.

**Comment by rachejazz** [comment]
Yeahh, also maybe link it the definition mentioned in FAQ section?
There's a "What's Software Discovery Tool?" there

**Comment by pleia2** [comment]
Maybe a blurb on the front page and then link out for more details? The FAQ need some work in this regard too, you don't get to the mention of architecture until the 4th question :sweat_smile:

**Comment by rachejazz** [comment]
Yess this can be done! After @indranilm256 gets the FAQ issue done, maybe i can take this up

**Comment by pleia2** [comment]
@rachejazz Want to move forward on this one once your FAQ work is done?

**Comment by rachejazz** [comment]
yep yep, I am solving these by today or tomorrow :)
