### ISSUE TITLE
FAQ fix-ups

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#56]
We have #36 to address operating systems, but the following version-related things should also be cleaned up in the FAQ:

- Improve description of the tool in the first question to mention that it's for s390x
- Remove version of tool in the first FAQ (it's neither useful nor accurate now)
- Remove supported browsers question entirely
- Remove mention of Intel architecture from the architecture question, it's just for s390x
- Anywhere it mentions "Linux distro" we can say something like "Linux distro or operating system" since we now include z/OS :smile:
- Update the links in the final question of the FAQ, developerworks is gone, probably want to link to the verified list at https://www.ibm.com/community/z/open-source-software/ and the new Z open source community on IBM Community https://www.ibm.com/community/z/open-source/

**Comment by indranilm256** [comment]
Will try to resolve this along with #36

**Comment by pleia2** [comment]
@indranilm256  Can you and @rachejazz work to divide the work here?

**Comment by rachejazz** [comment]
Cool, I'll get the last 3 done :D

**Comment by indranilm256** [comment]
First 4 fixed by PR https://github.com/openmainframeproject/software-discovery-tool/pull/58

**Comment by rachejazz** [comment]
All fixed after #61
