### ISSUE TITLE
Optimize cached_data.json creation

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool#73]
As discovered in an issue in our deployment on a small VM (https://github.com/openmainframeproject/software-discovery-tool-deploy/issues/5) the cached_data.json file creation will quietly fail if it takes too long (like on a server with not a lot of resources).

Since this is the only resource-intensive part of the tool, look into optimizing it, or lengthening the time it's allowed to take, in order for the operation to be completed on a system with fewer resources.

**Comment by rachejazz** [comment]
Can we just remove the cache mechanism?
Has it remotely ever been used? All the errors we faced till now happened due to this

**Comment by pleia2** [comment]
@arshPratap So I think the first thing to determine is how the cached_data.json file is being used. My assumption was that it was created from all the data sources, and then the tool read only from that cache file (rather than the several individual files), but we should actually confirm that this is the case. Once we know exactly what's going on, we can come up with a strategy to tackle it, whether it's removing usage of the cache file as @rachejazz suggests, or changing how it's generated, or even considering switching away from JSON as the format that the tool reads from (which could also be causing some of the slowness we're seeing while searching in production).

**Comment by arshPratap** [comment]
Closing in favour of #97
