### ISSUE TITLE
Installation  Issue 

### ISSUE THREAD

**Issue by Pratap2018** [openmainframeproject/software-discovery-tool#75]
## For Ubuntu 20.04  While installing the prerequisite  

```  
  sudo apt-get update
  sudo apt-get install -y python3 python3-pip gcc git python3-dev libssl-dev libffi-dev cron python3-lxml apache2 libapache2-mod-wsgi-py3
  sudo pip3 install 'cffi==1.11.5' 'cryptography==1.4' Flask launchpadlib simplejson requests pytest
```

- [x]   `sudo apt-get update`    Works perfectly
- [x]  `sudo apt-get install -y python3 python3-pip gcc git python3-dev libssl-dev libffi-dev cron python3-lxml apache2 libapache2-mod-wsgi-py3 `  Works perfectly     

- [x] `sudo pip3 install 'cffi==1.11.5' 'cryptography==1.4' Flask launchpadlib simplejson requests pytest
`
Not working **Fails to install cryptography and cffi** 

Error log is attached here

[error_install.log](https://github.com/openmainframeproject/software-discovery-tool/files/7596588/error_install.log)

**Comment by rachejazz** [comment]
does removing cffi and cryptography versions solve it?
Meaning try:
`sudo pip3 install cffi cryptography`

**Comment by Pratap2018** [comment]
@rachejazz  It Worked 
- [x] `sudo pip3 install cffi cryptography Flask launchpadlib simplejson requests pytest` works perfectly

**Comment by Pratap2018** [comment]
@rachejazz   
![Screenshot from 2021-11-25 10-20-50](https://user-images.githubusercontent.com/39677673/143381544-fd4b2456-bdd7-423e-b2ae-4293b0e79722.png)


in Step 5 docs/instalation.md this requires supersuser permission to work

**Comment by rachejazz** [comment]
Ah, yes the `/opt` directory is owned by root
I haven't mentioned use sudo because you can optionally keep that directory as writable by anyone

**Comment by rachejazz** [comment]
Problem looks solved :)
Solution: install pkg with latest version. Closing!
