### ISSUE TITLE
Proper Solution for updating debian ftp links

### ISSUE THREAD

**Issue by arshPratap** [openmainframeproject/software-discovery-tool#86]
**Description** : In the latest debian [releases](https://ftp.debian.org/debian/) for Buster and Bullseye (both dated on 26th April, 2022), the debian versions were changed as follows :

- Buster (v10.12) was released
- Bullseye (v11.3) was released

These frequent changes to the debian versions can cause future users to suffer from an issue similar to the one raised in #83. To counter this issue , a [suggestion](https://github.com/openmainframeproject/software-discovery-tool/pull/84#pullrequestreview-913243990) was raised by @rachejazz  in the PR(#84 ) to make some  changes to the debian links / process of acquiring the said debian links so as to make them "version-blind"

**Potential Solution** : I believe the easiest way to counter this issue would be to change the links that we have used [here](https://github.com/openmainframeproject/software-discovery-tool/blob/master/bin/package_build.py#L20) to change them to the following links : 

- For Buster
  `https://ftp.debian.org/debian/dists/buster/main/binary-s390x/Packages.gz`
- For Bullseye
  `https://ftp.debian.org/debian/dists/bullseye/main/binary-s390x/Packages.gz`
The reason why the said changes work is that the new links will directly redirect us to the latest debian binaries for s-390x and hence we would not have to change the link each and everytime a new debian update is released

I would love to work on this issue and also listen your suggestions to improve the solution for this issue.
Thanks

**Comment by rachejazz** [comment]
That should work! Assigning you. Good work :))

**Comment by arshPratap** [comment]
Closing in favor of #87 .
Thanks again !
